[tox]
envlist = qa, unit, integration, type, mutate, format

[testenv]
passenv = OTEL_TEST_RUN_ID
deps =
    pytest
    hypothesis
    pytest-mock
    pytest-asyncio
    pytest-benchmark
    coverage
    mutmut
    mypy
    ruff
commands = pytest {posargs}

[testenv:unit]
commands = coverage run -m pytest tests/unit

[testenv:integration]
commands = coverage run -m pytest tests/integration

[testenv:type]
commands = mypy -p tns_custom_metrics -p tests

[testenv:mutate]
commands = mutmut run --paths-to-mutate tns_custom_metrics --timeout 60 --runner 'pytest -q'

[testenv:format]
commands = ruff --fix tns_custom_metrics tests

[testenv:qa]
commands =
    ruff tns_custom_metrics tests
    mypy -p tns_custom_metrics -p tests
    coverage run -m pytest tests
    coverage xml -o reports/coverage/coverage.xml
    mutmut run --paths-to-mutate tns_custom_metrics --timeout 60 --runner 'pytest -q' --nice
