# Generated by Django 4.2.17 on 2025-07-01 21:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("release_date", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Feature Release",
                "verbose_name_plural": "Feature Releases",
                "ordering": ["-release_date"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("team", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=50)),
                ("organization", models.CharField(blank=True, max_length=100)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tns_custom_metrics_user_groups",
                        to="auth.group",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tns_custom_metrics_user_permissions",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["team", "username"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("event_type", models.CharField(max_length=10)),
                (
                    "device_vendor",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("device_type", models.CharField(blank=True, max_length=50, null=True)),
                ("module", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="tns_custom_metrics.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Interaction",
                "verbose_name_plural": "User Interactions",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp"], name="tns_custom__timesta_11240c_idx"
                    ),
                    models.Index(
                        fields=["user", "event_type"],
                        name="tns_custom__user_id_b937da_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SessionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="tns_custom_metrics.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Session Record",
                "verbose_name_plural": "Session Records",
                "indexes": [
                    models.Index(
                        fields=["start", "end"], name="tns_custom__start_7ba99c_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FeatureUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("feature_name", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("module", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_usages",
                        to="tns_custom_metrics.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Usage",
                "verbose_name_plural": "Feature Usages",
                "indexes": [
                    models.Index(
                        fields=["feature_name", "timestamp"],
                        name="tns_custom__feature_9375cb_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="APIRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("endpoint", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_requests",
                        to="tns_custom_metrics.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Request",
                "verbose_name_plural": "API Requests",
                "indexes": [
                    models.Index(
                        fields=["endpoint", "timestamp"],
                        name="tns_custom__endpoin_bc5b3b_idx",
                    )
                ],
            },
        ),
    ]
